# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven version check
        run: mvn -X -version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Mod
        working-directory: spectre
        run: ./gradlew collectArtifacts
      - name: Capture artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            spectre/artifacts
